--[[ ===================================================== ]] --
--[[               MH Parking V2 by MaDHouSe79             ]] --
--[[ ===================================================== ]] --
LocalVehicles, GlobalVehicles, isLoggedIn, SpawnedVehicles, DeletingEntities, displayOwnerText = {}, {}, false, false, false, Config.UseVehicleOwnerText
AddEventHandler('onResourceStop', function(resource) if resource == GetCurrentResourceName() then Parking.Functions.DeleteAllVehicles() PlayerData = {} isLoggedIn = false end end)
AddEventHandler('onResourceStart', function(resource) if resource == GetCurrentResourceName() then TriggerServerEvent('mh-parkingV2:server:OnJoin') PlayerData = GetPlayerData() isLoggedIn = true end end)
RegisterNetEvent(OnPlayerLoaded, function() TriggerServerEvent('mh-parkingV2:server:OnJoin') end)
RegisterNetEvent(OnPlayerUnload, function() Parking.Functions.DeleteAllVehicles() PlayerData = {} isLoggedIn = false end)
RegisterNetEvent("mh-parkingV2:client:RefreshVehicles", function(vehicles) Parking.Functions.RefreshVehicles(vehicles) end)
RegisterNetEvent("mh-parkingV2:client:AddVehicle", function(vehicle, playerId) Parking.Functions.AddVehicle(vehicle, playerId) end)
RegisterNetEvent("mh-parkingV2:client:DeleteVehicle", function(vehicle) Parking.Functions.DeleteLocalVehicle(vehicle) end)
RegisterNetEvent("mh-parkingV2:client:CreateOwnerVehicleBlip", function(data) Parking.Functions.CreateOwnerVehicleBlip(data) end)
RegisterNetEvent('mh-parkingV2:client:GetVehicleMenu', function() Parking.Functions.GetVehicleMenu() end)
RegisterNetEvent('mh-parkingV2:client:OnJoin', function() Parking.Functions.OnJoin() end)
RegisterNetEvent("mh-parkingV2:client:AutoPark", function(driver) Parking.Functions.AutoPark(driver) end)
RegisterNetEvent("mh-parkingV2:client:AutoDrive", function(driver) Parking.Functions.AutoDrive(driver) end)
RegisterCommand('toggleparktext', function() displayOwnerText = not displayOwnerText end, false)
RegisterCommand('parkmenu', function() TriggerEvent('mh-parkingV2:client:GetVehicleMenu') end, false)
CreateThread(function() while true do Wait(0) if isLoggedIn and displayOwnerText then Parking.Functions.DisplayVehicleOwnerText() end end end)
CreateThread(function() while true do Wait(2000) if isLoggedIn then if #LocalVehicles ~= 0 then Parking.Functions.MakeVehiclesVisable() end end end end)
CreateThread(function() while true do Wait(3000) if isLoggedIn then if #LocalVehicles ~= 0 then Parking.Functions.CheckDistanceToForceGrounded() end end end end)
CreateThread(function() while true do Wait(1000) if isLoggedIn then if #LocalVehicles ~= 0 then Parking.Functions.UpdateVehicleStatus() end collectgarbage("collect") end end end)
CreateThread(function() while true do Wait(0) if isLoggedIn then Parking.Functions.GetInAndOutVehicle() Wait(50) end end end)
CreateThread(function() while true do Wait(0) if isLoggedIn then Parking.Functions.KeepEngineRunning() end end end)
CreateThread(function() Parking.Functions.DisableParkedVehiclesCollision() end)
CreateThread(function() Parking.Functions.SpawnVehicleChecker() end)
CreateThread(function() Parking.Functions.CheckSteeringAngle() end)
CreateThread(function() Parking.Functions.RadialMenu() end)
CreateThread(function() Parking.Functions.CreateBlips() end)
CreateThread(function() Parking.Functions.AttachedToTrailer() end)
CreateThread(function() Parking.Functions.LoadTarget() end)