--[[ ===================================================== ]] --
--[[       MH Realistic Parking V2 Script by MaDHouSe      ]] --
--[[ ===================================================== ]] --
AddEventHandler('onResourceStart', function(resource) if resource == GetCurrentResourceName() then PlayerData, isLoggedIn = GetPlayerData(), true TriggerServerEvent('mh-parkingV2:server:OnJoin') Wait(50) TriggerServerEvent("mh-parkingV2:server:LoadVehiclesOnStart") end end)
AddEventHandler('onResourceStop', function(resource) if resource == GetCurrentResourceName() then  PlayerData, isLoggedIn = {}, false Parking.Functions.DeleteAllDisableParkedBlips() end end)
RegisterNetEvent(OnPlayerLoaded, function() PlayerData, isLoggedIn = GetPlayerData(), true TriggerServerEvent('mh-parkingV2:server:OnJoin') Wait(50) TriggerServerEvent("mh-parkingV2:server:RefreshVehicles") end)
RegisterNetEvent(OnPlayerUnload, function() PlayerData, isLoggedIn = {}, false Parking.Functions.DeleteAllDisableParkedBlips() end)
RegisterNetEvent(OnJobUpdate, function(job) SetJob(job) end)
RegisterNetEvent("mh-parkingV2:client:RefreshVehicles", function(vehicles) Parking.Functions.RemoveVehicles(vehicles) Wait(1000) Parking.Functions.SpawnVehicles(vehicles) end)
RegisterNetEvent("mh-parkingV2:client:Notify", function(message, type, length) Notify(message, type, length) end)
RegisterNetEvent("mh-parkingV2:client:DeletePlate", function(plate) Parking.Functions.DeleteLocalVehicle(plate) end)
RegisterNetEvent("mh-parkingV2:client:AddVehicle", function(data) Parking.Functions.AddParkedVehicle(data.entity, data) end)
RegisterNetEvent("mh-parkingV2:client:AutoPark", function(driver, netid) Parking.Functions.AutoPark(driver, netid) end)
RegisterNetEvent("mh-parkingV2:client:AutoDrive", function(driver, netid) Parking.Functions.AutoDrive(driver, netid) end)
RegisterNetEvent('mh-parkingV2:client:GetVehicleMenu', function() Parking.Functions.GetVehicleMenu() end)
RegisterNetEvent('mh-parkingV2:client:ClearAllSeats', function(netid) Parking.Functions.ClearAllSeats(netid) end)
RegisterNetEvent('mh-parkingV2:client:OnJoin', function(data) Parking.Functions.OnJoin(data) end)
RegisterCommand('toggleparktext', function() displayOwnerText = not displayOwnerText end, false)
RegisterCommand('parkmenu', function() TriggerEvent('mh-parkingV2:client:GetVehicleMenu') end, false)
CreateThread(function() Parking.Functions.RadialMenu() end)
CreateThread(function() Parking.Functions.CreateBlips() end)
CreateThread(function() Parking.Functions.CheckVehicleSteeringAngle() end)
CreateThread(function() while true do Wait(2000) if isLoggedIn then Parking.Functions.MakeVehiclesVisable() end end end)
CreateThread(function() while true do Wait(3000) if isLoggedIn then Parking.Functions.CheckDistanceToForceGrounded() end end end)
CreateThread(function() while true do Wait(0) if isLoggedIn then Parking.Functions.GetInAndOutVehicle() Wait(50) end end end)
CreateThread(function() while true do Wait(0) if isLoggedIn then Parking.Functions.KeepEngineRunning() end end end)
CreateThread(function() while true do if isLoggedIn and displayOwnerText then Parking.Functions.DisplayOwnerText() end Wait(0) end end)
CreateThread(function() while true do sleep = 100 if isLoggedIn and disableControll then sleep = 0 Parking.Functions.DisableControll() end Wait(sleep) end end)
