--[[ ===================================================== ]] --
--[[       MH Realistic Parking V2 Script by MaDHouSe      ]] --
--[[ ===================================================== ]] --
AddEventHandler('onResourceStart', function(resource) if resource == GetCurrentResourceName() then PlayerData, isLoggedIn = GetPlayerData(), true TriggerServerEvent("mh-parkingV2:server:refreshVehiclesOnStart") end end)
AddEventHandler('onResourceStop', function(resource) if resource == GetCurrentResourceName() then  PlayerData, isLoggedIn = {}, false Parking.Functions.DeleteAllDisableParkedBlips() end end)
RegisterNetEvent(OnPlayerLoaded, function() PlayerData, isLoggedIn = GetPlayerData(), true TriggerServerEvent("mh-parkingV2:server:refreshVehicles") end)
RegisterNetEvent(OnPlayerUnload, function() PlayerData, isLoggedIn = {}, false Parking.Functions.DeleteAllDisableParkedBlips() end)
RegisterNetEvent(OnJobUpdate, function(job) SetJob(job) end)
RegisterNetEvent("mh-parkingV2:client:refreshVehicles", function(vehicles) Parking.Functions.RemoveVehicles(vehicles) Wait(1000) Parking.Functions.SpawnVehicles(vehicles) end)
RegisterNetEvent("mh-parkingV2:client:notify", function(message, type, length) Notify(message, type, length) end)
RegisterNetEvent("mh-parkingV2:client:deletePlate", function(plate) Parking.Functions.DeleteLocalVehicle(plate) end)
RegisterNetEvent("mh-parkingV2:client:addVehicle", function(data) Parking.Functions.AddParkedVehicle(data.entity, data) end)
RegisterNetEvent("mh-parkingV2:client:autoPark", function(driver, netid) Parking.Functions.AutoPark(driver, netid) end)
RegisterNetEvent("mh-parkingV2:client:autoDrive", function(driver, netid) Parking.Functions.AutoDrive(driver, netid) end)
RegisterNetEvent('mh-parkingV2:client:GetVehicleMenu', function() Parking.Functions.GetVehicleMenu() end)
RegisterNetEvent('mh-parkingV2:client:GetOutVehicle', function(netid) Parking.Functions.GetOutVehicle(netid) end)
RegisterCommand('toggleparktext', function() displayOwnerText = not displayOwnerText end, false)
RegisterCommand('parkmenu', function() TriggerEvent('mh-parkingV2:client:GetVehicleMenu') end, false)
CreateThread(function() Parking.Functions.RadialMenu() end)
CreateThread(function() Parking.Functions.CreateBlips() end)
CreateThread(function() while true do Wait(2000) if isLoggedIn then Parking.Functions.MakeVehiclesVisable() end end end)
CreateThread(function() while true do Wait(3000) if isLoggedIn then Parking.Functions.CheckDistanceToForceGrounded() end end end)
CreateThread(function() while true do Wait(0) if isLoggedIn then Parking.Functions.GetInAndOutVehicle() Wait(50) end end end)
CreateThread(function() while true do Wait(0) if isLoggedIn then Parking.Functions.KeepEngineRunning() end end end)
CreateThread(function() while true do if displayOwnerText then Parking.Functions.DisplayOwnerText() end Wait(0) end end)
