--[[ ===================================================== ]] --
--[[       MH Realistic Parking V2 Script by MaDHouSe      ]] --
--[[ ===================================================== ]] --
Config = {}                             -- Placeholder don't edit or change or remove this.
Config.Debug = false                    -- Default false, if true this will show prints in the server console.
----------------------------------------------------------------------------
-- Framework (Do not change this)
Config.Framework = nil
if GetResourceState("es_extended") ~= 'missing' then
    Config.Framework = 'esx'
elseif GetResourceState("qb-core") ~= 'missing' then
    Config.Framework = 'qb'
elseif GetResourceState("qbx-core") ~= 'missing' then
    Config.Framework = 'qbx'
end
----------------------------------------------------------------------------
-- Target Script
Config.UseTarget = GetConvar('UseTarget', 'false') == 'true'
Config.TargetScript = "qb-target"          -- Default qb-target but you can also use ox_target.
----------------------------------------------------------------------------
-- Fuel Script
Config.FuelScript = 'LegacyFuel'           -- Default is LegacyFuel, if you use a other fuel script, for example ox_fuel
----------------------------------------------------------------------------
-- Notify Script
Config.DisableParkNotify = false           -- Default true, if false you get many notifications when you enter or leave the vehicle, all other notify massages are stil enable.
Config.NotifyScript = "ox_lib"             -- Default ox_lib, but you can use this scripts aswell (k5_notify, okokNotify, Roda_Notifications)
----------------------------------------------------------------------------
Config.OnlyAutoParkWhenEngineIsOff = true  -- Default true, if true auto park only when vehicle engine is off.
----------------------------------------------------------------------------
Config.ForceVehicleOnGound = true          -- If true this will force parked vehicles on the ground, sometimes the vehicles are in the air and by enable this is force the vehicle to the ground
----------------------------------------------------------------------------
-- For performance
Config.ViewDistance = true                 -- If true vehicles are only visable in 100 meters around the players.
Config.ParkedViewDistance = 100            -- Default 100 if your distance is over 100 meters the vehicles in that area will not render on screen.
Config.UseParkedBlips = true               -- if true players can see a blip of the parked vehicle on the map
Config.Maxparking = 2                      -- Default 1, this is max parked vehicles allowed per player, don't go to high with this...
Config.UseAsVip = false                    -- if true `Config.Maxparking` does not work and you need to add a amount per player.
----------------------------------------------------------------------------
Config.UseVehicleOwnerText = false
Config.VehicleOwnerTextDisplayDistance = 15
----------------------------------------------------------------------------
-- Stuff to automatic disable the auto parking system.
Config.DebugBlipForRadius = true   -- If true you see a circle aera on the map, use this for debug only.
Config.UseUnableParkingBlips = true -- If this you see blip for radius in the map.
Config.UseParkingLotsBlips = true  --If true players see parking lot blips on the map


-- This is when you need to use a atm, you can't use the auto park system.
-- This goes automatic so leave it as it is.
Config.ATMModels = {
    ['prop_atm_02'] = true,
    ['prop_atm_03'] = true,
    ['prop_fleeca_atm'] = true,
}

-- This is when you close to a gasstation, you can't use the auto park system.
-- This goes automatic so leave it as it is.
Config.DisableNeedByPumpModels = {
    ['prop_vintage_pump'] = true,
    ['prop_gas_pump_1a'] = true,
    ['prop_gas_pump_1b'] = true,
    ['prop_gas_pump_1c'] = true,
    ['prop_gas_pump_1d'] = true,
    ['prop_gas_pump_old2'] = true,
    ['prop_gas_pump_old3'] = true
}

-- This are locations where you can't use the auto park system.
-- the reason for this is it can be that you need to use the vehicle on that point.
-- So if you want that, you can't use the park system cause you can't use the vehicle when parked.
-- If you want to see the radius on the map you need to set Config.DebugBlipForRadius to true
Config.NoParkingLocations = {
    -- Default locations
    {coords = vector3(-333.0179, -135.5331, 38.3735), radius = 15.0, color = 1, sprite = 163, job = 'mechanic'},   -- ls costum 1
    {coords = vector3(731.7255, -1088.9088, 21.30), radius = 10.0, color = 1, sprite = 163, job = 'mechanic'},     -- ls costum 2
    {coords = vector3(-1155.3927, -2008.8042, 12.8369), radius = 15.0, color = 1, sprite = 163, job = 'mechanic'}, -- ls costum 3
    {coords = vector3(1178.6400, 2639.0259, 37.7538), radius = 15.0, color = 1, sprite = 163, job = 'mechanic'},   -- ls costum 4
    {coords = vector3(107.4339, 6624.6465, 31.7872), radius = 15.0, color = 1, sprite = 163, job = 'mechanic'},    -- ls costum 5
    {coords = vector3(-212.2455, -1325.4657, 30.2536), radius = 18.0, color = 1, sprite = 163, job = 'mechanic'},  -- bennys
    {coords = vector3(477.6514, -1021.8871, 27.3948), radius = 20.0, color = 1, sprite = 163, job = 'police'},     -- police back gate
    {coords = vector3(291.2697, -587.2904, 42.5459), radius = 15.0, color = 1, sprite = 163, job = 'ambulance'},   -- hospital front door
    {coords = vector3(408.9072, -1639.3105, 28.6553), radius = 25.0, color = 1, sprite = 163, job = nil},          -- Impound
    {coords = vector3(-644.0579, -232.3487, 37.1400), radius = 30.0, color = 1, sprite = 163, job = nil},          -- Jewelery
    {coords = vector3(-614.0209, -279.3901, 38.1910), radius = 30.0, color = 1, sprite = 163, job = nil},          -- Jewelery
    {coords = vector3(539.6107, -181.2838, 53.8477), radius = 30.0, color = 1, sprite = 163, job = 'mechanic'},    -- a mechanic shop close by the highway
    -- Car lift locations (mh-carlift)
    {coords = vector3(2345.31, 3141.512, 47.37874), radius = 10.0, color = 1, sprite = 163, job = 'scraptard'},    -- scraptard pos 1 (in de hal) (left)
    {coords = vector3(2358.866, 3139.057, 47.37369), radius = 10.0, color = 1, sprite = 163, job = 'scraptard'},   -- scraptard pos 2 (in de hal) (right)
    {coords = vector3(2333.153, 3042.031, 47.31144), radius = 10.0, color = 1, sprite = 163, job = 'scraptard'},   -- scraptard pos 3 (outside) (left)
    {coords = vector3(2339.808, 3042.183, 47.3141), radius = 10.0, color = 1, sprite = 163, job = 'scraptard'},    -- scraptard pos 4 (outside) (right)
    -- you can add more locations here.

}

---------------------------------------Parking lots-------------------------------------
-- Parking lots
-- If false players can park anyware, if true they can park only on parkinglots.
-- Players are not allwed to park close by -> (Config.DisableNeedByLocations or Config.DisableNeedByPumpModels)
-- If you want to see the radius in the map you need to set Config.DebugBlipForRadius to true
Config.UseParkingLotsOnly = false
Config.AllowedParkingLots = {
    {coords = vector3(96.9411, -1402.1882, 28.5636), radius = 10.0, color = 2, sprite = 237},   -- parkinglot 1
    {coords = vector3(228.7590, -786.5502, 30.0108), radius = 40.0, color = 2, sprite = 237},   -- parkinglot 2
    {coords = vector3(40.5961, -869.4373, 29.8342), radius = 30.0, color = 2, sprite = 237},    -- parkinglot 3
    {coords = vector3(-318.9083, -763.3641, 33.3298), radius = 50.0, color = 2, sprite = 237},  -- parkinglot 4
    {coords = vector3(-323.1429, -909.4062, 30.4433), radius = 50.0, color = 2, sprite = 237},  -- parkinglot 5
    {coords = vector3(140.4888, -1072.2378, 28.5544), radius = 50.0, color = 2, sprite = 237},  -- parkinglot 6
    {coords = vector3(16.6738, -1735.4730, 28.6658), radius = 40.0, color = 2, sprite = 237},   -- parkinglot 7
    {coords = vector3(280.1839, -332.9366, 44.2822), radius = 20.0, color = 2, sprite = 237},   -- parkinglot 8
    {coords = vector3(65.4638, 24.4819, 68.9776), radius = 15.0, color = 2, sprite = 237},      -- parkinglot 9
    {coords = vector3(-1136.9712, -753.5242, 18.7554), radius = 17.0, color = 2, sprite = 237}, -- parkinglot 10
    {coords = vector3(1702.2766, 3769.2583, 33.8426), radius = 10.0, color = 2, sprite = 237},  -- parkinglot 11
    {coords = vector3(45.9778, 6376.5962, 30.5970), radius = 20.0, color = 2, sprite = 237},    -- parkinglot 12
    {coords = vector3(-759.9047, 5537.7280, 32.8484), radius = 20.0, color = 2, sprite = 237},  -- parkinglot 13
    {coords = vector3(-464.8556, -769.8253, 29.9245), radius = 20.0, color = 2, sprite = 237},  -- parkinglot 14
    {coords = vector3(253.9985, -1156.1332, 28.6003), radius = 15.0, color = 2, sprite = 237},  -- parkinglot 15
    {coords = vector3(1183.6377, -1550.7142, 34.1825), radius = 20.0, color = 2, sprite = 237}, -- parkinglot 16
    {coords = vector3(131.8025, -712.3470, 32.4903), radius = 50.0, color = 2, sprite = 237},   -- parkinglot 17
    -- you can add more parking lot locations here.
}


Config.Vehicles = {
    --- Compacts (0)
    { model = 'asbo',            name = 'Asbo',                          brand = 'Maxwell'},
    { model = 'blista',          name = 'Blista',                        brand = 'Dinka'},
    { model = 'brioso',          name = 'Brioso R/A',                    brand = 'Grotti'},
    { model = 'club',            name = 'Club',                          brand = 'BF'},
    { model = 'dilettante',      name = 'Dilettante',                    brand = 'Karin'},
    { model = 'dilettante2',     name = 'Dilettante Patrol',             brand = 'Karin'},
    { model = 'kanjo',           name = 'Blista Kanjo',                  brand = 'Dinka'},
    { model = 'issi2',           name = 'Issi',                          brand = 'Weeny'},
    { model = 'issi3',           name = 'Issi Classic',                  brand = 'Weeny'},
    { model = 'issi4',           name = 'Issi Arena',                    brand = 'Weeny'},
    { model = 'issi5',           name = 'Issi Future Shock',             brand = 'Weeny'},
    { model = 'issi6',           name = 'Issi Nightmare',                brand = 'Weeny'},
    { model = 'panto',           name = 'Panto',                         brand = 'Benefactor'},
    { model = 'prairie',         name = 'Prairie',                       brand = 'Bollokan'},
    { model = 'rhapsody',        name = 'Rhapsody',                      brand = 'Declasse'},
    { model = 'brioso2',         name = 'Brioso 300',                    brand = 'Grotti'},
    { model = 'weevil',          name = 'Weevil',                        brand = 'BF'},
    { model = 'issi7',           name = 'Issi Sport',                    brand = 'Weeny'},
    { model = 'blista2',         name = 'Blista Compact',                brand = 'Dinka'},
    { model = 'blista3',         name = 'Blista Go Go Monkey',           brand = 'Dinka'},
    { model = 'brioso3',         name = 'Brioso 300 Widebody',           brand = 'Grotti'},
    { model = 'boor',            name = 'Boor',                          brand = 'Karin'},
    --- Sedans (1)
    { model = 'asea',            name = 'Asea',                          brand = 'Declasse'},
    { model = 'asterope',        name = 'Asterope',                      brand = 'Karin'},
    { model = 'cog55',           name = 'Cognoscenti 55',                brand = 'Enus'},
    { model = 'cognoscenti',     name = 'Cognoscenti',                   brand = 'Enus'},
    { model = 'emperor',         name = 'Emperor',                       brand = 'Albany'},
    { model = 'fugitive',        name = 'Fugitive',                      brand = 'Cheval'},
    { model = 'glendale',        name = 'Glendale',                      brand = 'Benefactor'},
    { model = 'glendale2',       name = 'Glendale Custom',               brand = 'Benefactor'},
    { model = 'ingot',           name = 'Ingot',                         brand = 'Vulcar'},
    { model = 'intruder',        name = 'Intruder',                      brand = 'Karin'},
    { model = 'premier',         name = 'Premier',                       brand = 'Declasse'},
    { model = 'primo',           name = 'Primo',                         brand = 'Albany'},
    { model = 'primo2',          name = 'Primo Custom',                  brand = 'Albany'},
    { model = 'regina',          name = 'Regina',                        brand = 'Dundreary'},
    { model = 'stafford',        name = 'Stafford',                      brand = 'Enus'},
    { model = 'stanier',         name = 'Stanier',                       brand = 'Vapid'},
    { model = 'stratum',         name = 'Stratum',                       brand = 'Zirconium'},
    { model = 'stretch',         name = 'Stretch',                       brand = 'Dundreary'},
    { model = 'superd',          name = 'Super Diamond',                 brand = 'Enus'},
    { model = 'surge',           name = 'Surge',                         brand = 'Cheval'},
    { model = 'tailgater',       name = 'Tailgater',                     brand = 'Obey'},
    { model = 'warrener',        name = 'Warrener',                      brand = 'Vulcar'},
    { model = 'washington',      name = 'Washington',                    brand = 'Albany'},
    { model = 'tailgater2',      name = 'Tailgater S',                   brand = 'Obey'},
    { model = 'cinquemila',      name = 'Lampadati',                     brand = 'Cinquemila'},
    { model = 'iwagen',          name = 'Obey',                          brand = 'I-Wagen'},
    { model = 'astron',          name = 'Astron',                        brand = 'Pfister'},
    { model = 'baller7',         name = 'Baller ST',                     brand = 'Gallivanter'},
    { model = 'comet7',          name = 'Comet',                         brand = 'S2 Cabrio'},
    { model = 'deity',           name = 'Deity',                         brand = 'Enus'},
    { model = 'jubilee',         name = 'Jubilee',                       brand = 'Enus'},
    { model = 'oracle',          name = 'Oracle',                        brand = 'Übermacht'},
    { model = 'schafter2',       name = 'Schafter',                      brand = 'Benefactor'},
    { model = 'warrener2',       name = 'Warrener HKR',                  brand = 'Vulcar'},
    { model = 'rhinehart',       name = 'Rhinehart',                     brand = 'Übermacht'},
    { model = 'eudora',          name = 'Eudora',                        brand = 'Willard'},
    { model = 'asterope2',       name = 'Asterope GZ',                   brand = 'Karin'},
    { model = 'impaler5',        name = 'Impaler SZ',                    brand = 'Declasse'},
    --- SUV (2)
    { model = 'demonhawkk',      name = 'Demon Hawk',                    brand = 'Jeep'},
    { model = 'baller',          name = 'Baller',                        brand = 'Gallivanter'},
    { model = 'baller2',         name = 'Baller II',                     brand = 'Gallivanter'},
    { model = 'baller3',         name = 'Baller LE',                     brand = 'Gallivanter'},
    { model = 'baller4',         name = 'Baller LE LWB',                 brand = 'Gallivanter'},
    { model = 'baller5',         name = 'Baller LE (Armored)',           brand = 'Gallivanter'},
    { model = 'baller6',         name = 'Baller LE LWB (Armored)',       brand = 'Gallivanter'},
    { model = 'bjxl',            name = 'BeeJay XL',                     brand = 'Karin'},
    { model = 'cavalcade',       name = 'Cavalcade',                     brand = 'Albany'},
    { model = 'cavalcade2',      name = 'Cavalcade II',                  brand = 'Albany'},
    { model = 'contender',       name = 'Contender',                     brand = 'Vapid'},
    { model = 'dubsta',          name = 'Dubsta',                        brand = 'Benefactor'},
    { model = 'dubsta2',         name = 'Dubsta Luxury',                 brand = 'Benefactor'},
    { model = 'fq2',             name = 'FQ2',                           brand = 'Fathom'},
    { model = 'granger',         name = 'Granger',                       brand = 'Declasse'},
    { model = 'gresley',         name = 'Gresley',                       brand = 'Bravado'},
    { model = 'habanero',        name = 'Habanero',                      brand = 'Emperor'},
    { model = 'huntley',         name = 'Huntley S',                     brand = 'Enus'},
    { model = 'landstalker',     name = 'Landstalker',                   brand = 'Dundreary'},
    { model = 'landstalker2',    name = 'Landstalker XL',                brand = 'Dundreary'},
    { model = 'novak',           name = 'Novak',                         brand = 'Lampadati'},
    { model = 'patriot',         name = 'Patriot',                       brand = 'Mammoth'},
    { model = 'patriot2',        name = 'Patriot Stretch',               brand = 'Mammoth'},
    { model = 'radi',            name = 'Radius',                        brand = 'Vapid'},
    { model = 'rebla',           name = 'Rebla GTS',                     brand = 'Übermacht'},
    { model = 'rocoto',          name = 'Rocoto',                        brand = 'Obey'},
    { model = 'seminole',        name = 'Seminole',                      brand = 'Canis'},
    { model = 'seminole2',       name = 'Seminole Frontier',             brand = 'Canis'},
    { model = 'serrano',         name = 'Serrano',                       brand = 'Benefactor'},
    { model = 'toros',           name = 'Toros',                         brand = 'Pegassi'},
    { model = 'xls',             name = 'XLS',                           brand = 'Benefactor'},
    { model = 'granger2',        name = 'Granger 3600LX',                brand = 'Declasse'},
    { model = 'patriot3',        name = 'Patriot Military',              brand = 'Mil-Spec'},
    { model = 'aleutian',        name = 'Aleutian',                      brand = 'Vapid'},
    { model = 'baller8',         name = 'Baller ST-D',                   brand = 'Gallivanter'},
    { model = 'cavalcade3',      name = 'Cavalcade XL',                  brand = 'Albany'},
    { model = 'dorado',          name = 'Dorado',                        brand = 'Bravado'},
    { model = 'vivanite',        name = 'Vivanite',                      brand = 'Karin'},
    { model = 'castigator',      name = 'Castigator',                    brand = 'Canis'},
    --- Coupes (3)
    { model = 'cogcabrio',       name = 'Cognoscenti Cabrio',            brand = 'Enus'},
    { model = 'exemplar',        name = 'Exemplar',                      brand = 'Dewbauchee'},
    { model = 'f620',            name = 'F620',                          brand = 'Ocelot'},
    { model = 'felon',           name = 'Felon',                         brand = 'Lampadati'},
    { model = 'felon2',          name = 'Felon GT',                      brand = 'Lampadati'},
    { model = 'jackal',          name = 'Jackal',                        brand = 'Ocelot'},
    { model = 'oracle2',         name = 'Oracle XS',                     brand = 'Übermacht'},
    { model = 'sentinel',        name = 'Sentinel',                      brand = 'Übermacht'},
    { model = 'sentinel2',       name = 'Sentinel XS',                   brand = 'Übermacht'},
    { model = 'windsor',         name = 'Windsor',                       brand = 'Enus'},
    { model = 'windsor2',        name = 'Windsor Drop',                  brand = 'Enus'},
    { model = 'zion',            name = 'Zion',                          brand = 'Übermacht'},
    { model = 'zion2',           name = 'Zion Cabrio',                   brand = 'Übermacht'},
    { model = 'previon',         name = 'Previon',                       brand = 'Karin'},
    { model = 'champion',        name = 'Champion',                      brand = 'Dewbauchee'},
    { model = 'futo',            name = 'Futo',                          brand = 'Karin'},
    { model = 'sentinel3',       name = 'Sentinel Classic',              brand = 'Übermacht'},
    { model = 'kanjosj',         name = 'Kanjo SJ',                      brand = 'Dinka'},
    { model = 'postlude',        name = 'Postlude',                      brand = 'Dinka'},
    { model = 'tahoma',          name = 'Tahoma Coupe',                  brand = 'Declasse'},
    { model = 'broadway',        name = 'Broadway',                      brand = 'Classique'},
    { model = 'fr36',            name = 'FR36',                          brand = 'Fathom'},
    --- Muscle (4)
    { model = 'blade',           name = 'Blade',                         brand = 'Vapid'},
    { model = 'buccaneer',       name = 'Buccaneer',                     brand = 'Albany'},
    { model = 'buccaneer2',      name = 'Buccaneer Rider',               brand = 'Albany'},
    { model = 'chino',           name = 'Chino',                         brand = 'Vapid'},
    { model = 'chino2',          name = 'Chino Luxe',                    brand = 'Vapid'},
    { model = 'clique',          name = 'Clique',                        brand = 'Vapid'},
    { model = 'coquette3',       name = 'Coquette BlackFin',             brand = 'Invetero'},
    { model = 'deviant',         name = 'Deviant',                       brand = 'Schyster'},
    { model = 'dominator',       name = 'Dominator',                     brand = 'Vapid'},
    { model = 'dominator2',      name = 'Pißwasser Dominator',           brand = 'Vapid'},
    { model = 'dominator3',      name = 'Dominator GTX',                 brand = 'Vapid'},
    { model = 'dominator4',      name = 'Dominator Arena',               brand = 'Vapid'},
    { model = 'dominator7',      name = 'Dominator ASP',                 brand = 'Vapid'},
    { model = 'dominator8',      name = 'Dominator GTT',                 brand = 'Vapid'},
    { model = 'dukes',           name = 'Dukes',                         brand = 'Imponte'},
    { model = 'dukes2',          name = 'Duke O\'Death',                 brand = 'Imponte'},
    { model = 'dukes3',          name = 'Beater Dukes',                  brand = 'Imponte'},
    { model = 'faction',         name = 'Faction',                       brand = 'Willard'},
    { model = 'faction2',        name = 'Faction Rider',                 brand = 'Willard'},
    { model = 'faction3',        name = 'Faction Custom Donk',           brand = 'Willard'},
    { model = 'ellie',           name = 'Ellie',                         brand = 'Vapid'},
    { model = 'gauntlet',        name = 'Gauntlet',                      brand = 'Bravado'},
    { model = 'gauntlet2',       name = 'Redwood Gauntlet',              brand = 'Bravado'},
    { model = 'gauntlet3',       name = 'Classic Gauntlet',              brand = 'Bravado'},
    { model = 'gauntlet4',       name = 'Gauntlet Hellfire',             brand = 'Bravado'},
    { model = 'gauntlet5',       name = 'Gauntlet Classic Custom',       brand = 'Bravado'},
    { model = 'hermes',          name = 'Hermes',                        brand = 'Albany'},
    { model = 'hotknife',        name = 'Hotknife',                      brand = 'Vapid'},
    { model = 'hustler',         name = 'Hustler',                       brand = 'Vapid'},
    { model = 'impaler',         name = 'Impaler',                       brand = 'Vapid'},
    { model = 'impaler2',        name = 'Impaler Arena',                 brand = 'Vapid'},
    { model = 'impaler3',        name = 'Impaler Future Shock',          brand = 'Vapid'},
    { model = 'impaler4',        name = 'Impaler Nightmare',             brand = 'Vapid'},
    { model = 'imperator',       name = 'Imperator Arena',               brand = 'Vapid'},
    { model = 'imperator2',      name = 'imperator Future Shock',        brand = 'Vapid'},
    { model = 'imperator3',      name = 'Imperator Nightmare',           brand = 'Vapid'},
    { model = 'lurcher',         name = 'Lurcher',                       brand = 'Bravado'},
    { model = 'nightshade',      name = 'Nightshade',                    brand = 'Imponte'},
    { model = 'phoenix',         name = 'Phoenix',                       brand = 'Imponte'},
    { model = 'picador',         name = 'Picador',                       brand = 'Cheval'},
    { model = 'ratloader2',      name = 'Ratloader',                     brand = 'Ratloader2'},
    { model = 'ruiner',          name = 'Ruiner',                        brand = 'Imponte'},
    { model = 'ruiner2',         name = 'Ruiner 2000',                   brand = 'Imponte'},
    { model = 'sabregt',         name = 'Sabre GT Turbo',                brand = 'Declasse'},
    { model = 'sabregt2',        name = 'Sabre GT Turbo Custom',         brand = 'Declasse'},
    { model = 'slamvan',         name = 'Slam Van',                      brand = 'Vapid'},
    { model = 'slamvan2',        name = 'Lost Slam Van',                 brand = 'Vapid'},
    { model = 'slamvan3',        name = 'Slam Van Custom',               brand = 'Vapid'},
    { model = 'stalion',         name = 'Stallion',                      brand = 'Declasse'},
    { model = 'stalion2',        name = 'Stallion Burgershot',           brand = 'Declasse'},
    { model = 'tampa',           name = 'Tampa',                         brand = 'Declasse'},
    { model = 'tulip',           name = 'Tulip',                         brand = 'Declasse'},
    { model = 'vamos',           name = 'Vamos',                         brand = 'Declasse'},
    { model = 'vigero',          name = 'Vigero',                        brand = 'Declasse'},
    { model = 'virgo',           name = 'Virgo',                         brand = 'Albany'},
    { model = 'virgo2',          name = 'Virgo Custom Classic',          brand = 'Dundreary'},
    { model = 'virgo3',          name = 'Virgo Classic',                 brand = 'Dundreary'},
    { model = 'voodoo',          name = 'Voodoo',                        brand = 'Declasse'},
    { model = 'yosemite',        name = 'Yosemite',                      brand = 'Declasse'},
    { model = 'yosemite2',       name = 'Yosemite Drift',                brand = 'Declasse'},
    { model = 'buffalo4',        name = 'Buffalo STX',                   brand = 'Bravado'},
    { model = 'manana',          name = 'Manana',                        brand = 'Albany'},
    { model = 'manana2',         name = 'Manana Custom',                 brand = 'Albany'},
    { model = 'tampa2',          name = 'Drift Tampa',                   brand = 'Declasse'},
    { model = 'ruiner4',         name = 'Ruiner ZZ-8',                   brand = 'Imponte'},
    { model = 'vigero2',         name = 'Vigero ZX',                     brand = 'Declasse'},
    { model = 'weevil2',         name = 'Weevil Custom',                 brand = 'BF'},
    { model = 'buffalo5',        name = 'Buffalo EVX',                   brand = 'Bravado'},
    { model = 'tulip2',          name = 'Tulip M-100',                   brand = 'Declasse'},
    { model = 'clique2',         name = 'Clique Wagon',                  brand = 'Vapid'},
    { model = 'brigham',         name = 'Brigham',                       brand = 'Albany'},
    { model = 'greenwood',       name = 'Greenwood',                     brand = 'Bravado'},
    { model = 'dominator9',      name = 'Dominator GT',                  brand = 'Vapid'},
    { model = 'impaler6',        name = 'Impaler LX',                    brand = 'Declasse'},
    { model = 'vigero3',         name = 'Vigero ZX Convertible',         brand = 'Declasse'},
    --- Sports Classic (5)
    { model = 'ardent',          name = 'Ardent',                        brand = 'Ocelot'},
    { model = 'btype',           name = 'Roosevelt',                     brand = 'Albany'},
    { model = 'btype2',          name = 'Franken Stange',                brand = 'Albany'},
    { model = 'btype3',          name = 'Roosevelt Valor',               brand = 'Albany'},
    { model = 'casco',           name = 'Casco',                         brand = 'Lampadati'},
    { model = 'deluxo',          name = 'Deluxo',                        brand = 'Imponte'},
    { model = 'dynasty',         name = 'Dynasty',                       brand = 'Weeny'},
    { model = 'fagaloa',         name = 'Fagaloa',                       brand = 'Vulcar'},
    { model = 'feltzer3',        name = 'Stirling GT',                   brand = 'Benefactor'},
    { model = 'gt500',           name = 'GT500',                         brand = 'Grotti'},
    { model = 'infernus2',       name = 'Infernus Classic',              brand = 'Pegassi'},
    { model = 'jb700',           name = 'JB 700',                        brand = 'Dewbauchee'},
    { model = 'jb7002',          name = 'JB 700W',                       brand = 'Dewbauchee'},
    { model = 'mamba',           name = 'Mamba',                         brand = 'Declasse'},
    { model = 'michelli',        name = 'Michelli GT',                   brand = 'Lampadati'},
    { model = 'monroe',          name = 'Monroe',                        brand = 'Pegassi'},
    { model = 'nebula',          name = 'Nebula',                        brand = 'Vulcar'},
    { model = 'peyote',          name = 'Peyote',                        brand = 'Vapid'},
    { model = 'peyote3',         name = 'Peyote Custom',                 brand = 'Vapid'},
    { model = 'pigalle',         name = 'Pigalle',                       brand = 'Lampadati'},
    { model = 'rapidgt3',        name = 'Rapid GT Classic',              brand = 'Dewbauchee'},
    { model = 'retinue',         name = 'Retinue',                       brand = 'Vapid'},
    { model = 'retinue2',        name = 'Retinue MKII',                  brand = 'Vapid'},
    { model = 'savestra',        name = 'Savestra',                      brand = 'Annis'},
    { model = 'stinger',         name = 'Stinger',                       brand = 'Grotti'},
    { model = 'stingergt',       name = 'Stinger GT',                    brand = 'Grotti'},
    { model = 'stromberg',       name = 'Stromberg',                     brand = 'Ocelot'},
    { model = 'swinger',         name = 'Swinger',                       brand = 'Ocelot'},
    { model = 'torero',          name = 'Torero',                        brand = 'Pegassi'},
    { model = 'tornado',         name = 'Tornado',                       brand = 'Declasse'},
    { model = 'tornado2',        name = 'Tornado Convertible',           brand = 'Declasse'},
    { model = 'tornado5',        name = 'Tornado Custom',                brand = 'Declasse'},
    { model = 'turismo2',        name = 'Turismo Classic',               brand = 'Grotti'},
    { model = 'viseris',         name = 'Viseris',                       brand = 'Lampadati'},
    { model = 'z190',            name = '190Z',                          brand = 'Karin'},
    { model = 'ztype',           name = 'Z-Type',                        brand = 'Truffade'},
    { model = 'zion3',           name = 'Zion Classic',                  brand = 'Übermacht'},
    { model = 'cheburek',        name = 'Cheburek',                      brand = 'Rune'},
    { model = 'toreador',        name = 'Toreador',                      brand = 'Pegassi'},
    { model = 'peyote2',         name = 'Peyote Gasser',                 brand = 'Vapid'},
    { model = 'coquette2',       name = 'Coquette Classic',              brand = 'Invetero'},
    { model = 'envisage',        name = 'Envisage',                      brand = 'Bollokan'},
    { model = 'driftnebula',     name = 'Nebula Turbo',                  brand = 'Vulcar'},
    --- Sports (6)
    { model = 'alpha',           name = 'Alpha',                         brand = 'Albany'},
    { model = 'banshee',         name = 'Banshee',                       brand = 'Bravado'},
    { model = 'bestiagts',       name = 'Bestia GTS',                    brand = 'Grotti'},
    { model = 'buffalo',         name = 'Buffalo',                       brand = 'Bravado'},
    { model = 'buffalo2',        name = 'Buffalo S',                     brand = 'Bravado'},
    { model = 'carbonizzare',    name = 'Carbonizzare',                  brand = 'Grotti'},
    { model = 'comet2',          name = 'Comet',                         brand = 'Pfister'},
    { model = 'comet3',          name = 'Comet Retro Custom',            brand = 'Pfister'},
    { model = 'comet4',          name = 'Comet Safari',                  brand = 'Pfister'},
    { model = 'comet5',          name = 'Comet SR',                      brand = 'Pfister'},
    { model = 'coquette',        name = 'Coquette',                      brand = 'Invetero'},
    { model = 'coquette4',       name = 'Coquette D10',                  brand = 'Invetero'},
    { model = 'drafter',         name = '8F Drafter',                    brand = 'Obey'},
    { model = 'elegy',           name = 'Elegy Retro Custom',            brand = 'Annis'},
    { model = 'elegy2',          name = 'Elegy RH8',                     brand = 'Annis'},
    { model = 'feltzer2',        name = 'Feltzer',                       brand = 'Benefactor'},
    { model = 'flashgt',         name = 'Flash GT',                      brand = 'Vapid'},
    { model = 'furoregt',        name = 'Furore GT',                     brand = 'Lampadati'},
    { model = 'gb200',           name = 'GB 200',                        brand = 'Vapid'},
    { model = 'komoda',          name = 'Komoda',                        brand = 'Lampadati'},
    { model = 'imorgon',         name = 'Imorgon',                       brand = 'Överflöd'},
    { model = 'italigto',        name = 'Itali GTO',                     brand = 'Progen'},
    { model = 'jugular',         name = 'Jugular',                       brand = 'Ocelot'},
    { model = 'jester',          name = 'Jester',                        brand = 'Dinka'},
    { model = 'jester2',         name = 'Jester Racecar',                brand = 'Dinka'},
    { model = 'jester3',         name = 'Jester Classic',                brand = 'Dinka'},
    { model = 'khamelion',       name = 'Khamelion',                     brand = 'Hijak'},
    { model = 'kuruma',          name = 'Kuruma',                        brand = 'Karin'},
    { model = 'kuruma2',         name = 'kuruma2',                       brand = 'Karin2'},
    { model = 'locust',          name = 'Locust',                        brand = 'Ocelot'},
    { model = 'lynx',            name = 'Lynx',                          brand = 'Ocelot'},
    { model = 'massacro',        name = 'Massacro',                      brand = 'Dewbauchee'},
    { model = 'massacro2',       name = 'Massacro Racecar',              brand = 'Dewbauchee'},
    { model = 'neo',             name = 'Neo',                           brand = 'Vysser'},
    { model = 'neon',            name = 'Neon',                          brand = 'Pfister'},
    { model = 'ninef',           name = '9F',                            brand = 'Obey'},
    { model = 'ninef2',          name = '9F Cabrio',                     brand = 'Obey'},
    { model = 'omnis',           name = 'Omnis',                         brand = 'Wow'},
    { model = 'paragon',         name = 'Paragon',                       brand = 'Enus'},
    { model = 'pariah',          name = 'Pariah',                        brand = 'Ocelot'},
    { model = 'penumbra',        name = 'Penumbra',                      brand = 'Maibatsu'},
    { model = 'penumbra2',       name = 'Penumbra FF',                   brand = 'Maibatsu'},
    { model = 'rapidgt',         name = 'Rapid GT',                      brand = 'Dewbauchee'},
    { model = 'rapidgt2',        name = 'Rapid GT Convertible',          brand = 'Dewbauchee'},
    { model = 'raptor',          name = 'Raptor',                        brand = 'BF'},
    { model = 'revolter',        name = 'Revolter',                      brand = 'Übermacht'},
    { model = 'ruston',          name = 'Ruston',                        brand = 'Hijak'},
    { model = 'schafter3',       name = 'Schafter V12',                  brand = 'Benefactor'},
    { model = 'schafter4',       name = 'Schafter LWB',                  brand = 'Benefactor'},
    { model = 'schlagen',        name = 'Schlagen GT',                   brand = 'Benefactor'},
    { model = 'schwarzer',       name = 'Schwartzer',                    brand = 'Benefactor'},
    { model = 'seven70',         name = 'Seven-70',                      brand = 'Dewbauchee'},
    { model = 'specter',         name = 'Specter',                       brand = 'Dewbauchee'},
    { model = 'streiter',        name = 'Streiter',                      brand = 'Benefactor'},
    { model = 'sugoi',           name = 'Sugoi',                         brand = 'Dinka'},
    { model = 'sultan',          name = 'Sultan',                        brand = 'Karin'},
    { model = 'sultan2',         name = 'Sultan Custom',                 brand = 'Karin'},
    { model = 'surano',          name = 'Surano',                        brand = 'Benefactor'},
    { model = 'tropos',          name = 'Tropos Rallye',                 brand = 'Lampadati'},
    { model = 'verlierer2',      name = 'Verlierer',                     brand = 'Bravado'},
    { model = 'vstr',            name = 'V-STR',                         brand = 'Albany'},
    { model = 'italirsx',        name = 'Itali RSX',                     brand = 'Progen'},
    { model = 'zr350',           name = 'ZR350',                         brand = 'Annis'},
    { model = 'calico',          name = 'Calico GTF',                    brand = 'Karin'},
    { model = 'futo2',           name = 'Futo GTX',                      brand = 'Karin'},
    { model = 'euros',           name = 'Euros',                         brand = 'Annis'},
    { model = 'jester4',         name = 'Jester RR',                     brand = 'Dinka'},
    { model = 'remus',           name = 'Remus',                         brand = 'Annis'},
    { model = 'comet6',          name = 'Comet S2',                      brand = 'Pfister'},
    { model = 'growler',         name = 'Growler',                       brand = 'Pfister'},
    { model = 'vectre',          name = 'Vectre',                        brand = 'Emperor'},
    { model = 'cypher',          name = 'Cypher',                        brand = 'Übermacht'},
    { model = 'sultan3',         name = 'Sultan Classic Custom',         brand = 'Karin'},
    { model = 'rt3000',          name = 'RT3000',                        brand = 'Dinka'},
    { model = 'sultanrs',        name = 'Sultan RS',                     brand = 'Karin'},
    { model = 'visione',         name = 'Visione',                       brand = 'Grotti'},
    { model = 'cheetah2',        name = 'Cheetah Classic',               brand = 'Grotti'},
    { model = 'stingertt',       name = 'Itali GTO Stinger TT',          brand = 'Maibatsu'},
    { model = 'omnisegt',        name = 'Omnis e-GT',                    brand = 'Obey'},
    { model = 'sentinel4',       name = 'Sentinel Classic Widebody',     brand = 'Übermacht'},
    { model = 'sm722',           name = 'SM722',                         brand = 'Benefactor'},
    { model = 'tenf',            name = '10F',                           brand = 'Obey'},
    { model = 'tenf2',           name = '10F Widebody',                  brand = 'Obey'},
    { model = 'everon2',         name = 'Everon Hotring',                brand = 'Karin'},
    { model = 'issi8',           name = 'Issi Rally',                    brand = 'Weeny'},
    { model = 'corsita',         name = 'Corsita',                       brand = 'Lampadati'},
    { model = 'gauntlet6',       name = 'Hotring Hellfire',              brand = 'Bravado'},
    { model = 'coureur',         name = 'La Coureuse',                   brand = 'Penaud'},
    { model = 'r300',            name = '300R',                          brand = 'Annis'},
    { model = 'panthere',        name = 'Panthere',                      brand = 'Toundra'},
    { model = 'driftsentinel',   name = 'Drift Sentinel Classic',        brand = 'Ubermacht'},
    { model = 'paragon3',        name = 'Paragon S',                     brand = 'Enus'},
    { model = 'eurosX32',        name = 'Euros X32',                     brand = 'Annis'},
    { model = 'vorschlaghammer', name = 'Vorschlaghammer',               brand = 'Pfister'},
    { model = 'driftcypher',     name = 'Drift Cypher',                  brand = 'Ubermacht'},
    { model = 'coquette5',       name = 'Coquette D1',                   brand = 'Invetero'},
    { model = 'pipistrello',     name = 'Pipistrello',                   brand = 'Overflod'},
    { model = 'niobe',           name = 'Niobe',                         brand = 'Ubermacht'},
    { model = 'driftvorschlag',  name = 'Vorschlaghammer',               brand = 'Pfister'},
    --- Super (7)
    { model = 'adder',           name = 'Adder',                         brand = 'Truffade'},
    { model = 'autarch',         name = 'Autarch',                       brand = 'Överflöd'},
    { model = 'banshee2',        name = 'Banshee 900R',                  brand = 'Bravado'},
    { model = 'bullet',          name = 'Bullet',                        brand = 'Vapid'},
    { model = 'cheetah',         name = 'Cheetah',                       brand = 'Grotti'},
    { model = 'cyclone',         name = 'Cyclone',                       brand = 'Coil'},
    { model = 'entity2',         name = 'Entity XXR',                    brand = 'Överflöd'},
    { model = 'entityxf',        name = 'Entity XF',                     brand = 'Överflöd'},
    { model = 'emerus',          name = 'Emerus',                        brand = 'Progen'},
    { model = 'fmj',             name = 'FMJ',                           brand = 'Vapid'},
    { model = 'furia',           name = 'Furia',                         brand = 'Grotti'},
    { model = 'gp1',             name = 'GP1',                           brand = 'Progen'},
    { model = 'infernus',        name = 'Infernus',                      brand = 'Pegassi'},
    { model = 'italigtb',        name = 'Itali GTB',                     brand = 'Progen'},
    { model = 'italigtb2',       name = 'Itali GTB Custom',              brand = 'Progen'},
    { model = 'krieger',         name = 'Krieger',                       brand = 'Benefactor'},
    { model = 'le7b',            name = 'RE-7B',                         brand = 'Annis'},
    { model = 'nero',            name = 'Nero',                          brand = 'Truffade'},
    { model = 'nero2',           name = 'Nero Custom',                   brand = 'Truffade'},
    { model = 'osiris',          name = 'Osiris',                        brand = 'Pegassi'},
    { model = 'penetrator',      name = 'Penetrator',                    brand = 'Ocelot'},
    { model = 'pfister811',      name = '811',                           brand = 'Pfister'},
    { model = 'prototipo',       name = 'X80 Proto',                     brand = 'Grotti'},
    { model = 'reaper',          name = 'Reaper',                        brand = 'Pegassi'},
    { model = 's80',             name = 'S80RR',                         brand = 'Annis'},
    { model = 'sc1',             name = 'SC1',                           brand = 'Übermacht'},
    { model = 'sheava',          name = 'ETR1',                          brand = 'Emperor'},
    { model = 't20',             name = 'T20',                           brand = 'Progen'},
    { model = 'taipan',          name = 'Taipan',                        brand = 'Cheval'},
    { model = 'tempesta',        name = 'Tempesta',                      brand = 'Pegassi'},
    { model = 'tezeract',        name = 'Tezeract',                      brand = 'Pegassi'},
    { model = 'thrax',           name = 'Thrax',                         brand = 'Truffade'},
    { model = 'tigon',           name = 'Tigon',                         brand = 'Lampadati'},
    { model = 'turismor',        name = 'Turismo R',                     brand = 'Grotti'},
    { model = 'tyrant',          name = 'Tyrant',                        brand = 'Överflöd'},
    { model = 'tyrus',           name = 'Tyrus',                         brand = 'Progen'},
    { model = 'vacca',           name = 'Vacca',                         brand = 'Pegassi'},
    { model = 'vagner',          name = 'Vagner',                        brand = 'Dewbauchee'},
    { model = 'voltic',          name = 'Voltic',                        brand = 'Coil'},
    { model = 'voltic2',         name = 'Rocket Voltic',                 brand = 'Coil'},
    { model = 'xa21',            name = 'XA-21',                         brand = 'Ocelot'},
    { model = 'zentorno',        name = 'Zentorno',                      brand = 'Pegassi'},
    { model = 'zorrusso',        name = 'Zorrusso',                      brand = 'Pegassi'},
    { model = 'ignus',           name = 'Ignus',                         brand = 'Pegassi'},
    { model = 'zeno',            name = 'Zeno',                          brand = 'Överflöd'},
    { model = 'deveste',         name = 'Deveste',                       brand = 'Principe'},
    { model = 'lm87',            name = 'LM87',                          brand = 'Benefactor'},
    { model = 'torero2',         name = 'Torero XO',                     brand = 'Pegassi'},
    { model = 'entity3',         name = 'Entity MT',                     brand = 'Overflod'},
    { model = 'virtue',          name = 'Virtue',                        brand = 'Ocelot'},
    { model = 'turismo3',        name = 'Turismo Omaggio',               brand = 'Grotti'},
    --- Motorcycles (8)
    { model = 'akuma',           name = 'Akuma',                         brand = 'Dinka'},
    { model = 'avarus',          name = 'Avarus',                        brand = 'LCC'},
    { model = 'bagger',          name = 'Bagger',                        brand = 'WMC'},
    { model = 'bati',            name = 'Bati 801',                      brand = 'Pegassi'},
    { model = 'bati2',           name = 'Bati 801RR',                    brand = 'Pegassi'},
    { model = 'bf400',           name = 'BF400',                         brand = 'Nagasaki'},
    { model = 'carbonrs',        name = 'Carbon RS',                     brand = 'Nagasaki'},
    { model = 'chimera',         name = 'Chimera',                       brand = 'Nagasaki'},
    { model = 'cliffhanger',     name = 'Cliffhanger',                   brand = 'Western'},
    { model = 'daemon',          name = 'Daemon',                        brand = 'WMC'},
    { model = 'daemon2',         name = 'Daemon Custom',                 brand = 'Western'},
    { model = 'defiler',         name = 'Defiler',                       brand = 'Shitzu'},
    { model = 'deathbike',       name = 'Deathbike Apocalypse',          brand = 'Deathbike'},
    { model = 'deathbike2',      name = 'Deathbike Future Shock',        brand = 'Deathbike'},
    { model = 'deathbike3',      name = 'Deathbike Nightmare',           brand = 'Deathbike'},
    { model = 'diablous',        name = 'Diablous',                      brand = 'Principe'},
    { model = 'diablous2',       name = 'Diablous Custom',               brand = 'Principe'},
    { model = 'double',          name = 'Double-T',                      brand = 'Dinka'},
    { model = 'enduro',          name = 'Enduro',                        brand = 'Dinka'},
    { model = 'esskey',          name = 'Esskey',                        brand = 'Pegassi'},
    { model = 'faggio',          name = 'Faggio Sport',                  brand = 'Pegassi'},
    { model = 'faggio2',         name = 'Faggio',                        brand = 'Pegassi'},
    { model = 'faggio3',         name = 'Faggio Mod',                    brand = 'Pegassi'},
    { model = 'fcr',             name = 'FCR 1000',                      brand = 'Pegassi'},
    { model = 'fcr2',            name = 'FCR 1000 Custom',               brand = 'Pegassi'},
    { model = 'gargoyle',        name = 'Gargoyle',                      brand = 'Western'},
    { model = 'hakuchou',        name = 'Hakuchou',                      brand = 'Shitzu'},
    { model = 'hakuchou2',       name = 'Hakuchou Drag',                 brand = 'Shitzu'},
    { model = 'hexer',           name = 'Hexer',                         brand = 'LCC'},
    { model = 'innovation',      name = 'Innovation',                    brand = 'LLC'},
    { model = 'lectro',          name = 'Lectro',                        brand = 'Principe'},
    { model = 'manchez',         name = 'Manchez',                       brand = 'Maibatsu'},
    { model = 'nemesis',         name = 'Nemesis',                       brand = 'Principe'},
    { model = 'nightblade',      name = 'Nightblade',                    brand = 'WMC'},
    { model = 'oppressor',       name = 'Oppressor',                     brand = 'Pegassi'},
    { model = 'pcj',             name = 'PCJ-600',                       brand = 'Shitzu'},
    { model = 'ratbike',         name = 'Rat Bike',                      brand = 'Western'},
    { model = 'ruffian',         name = 'Ruffian',                       brand = 'Pegassi'},
    { model = 'sanchez',         name = 'Sanchez Livery',                brand = 'Maibatsu'},
    { model = 'sanchez2',        name = 'Sanchez',                       brand = 'Maibatsu'},
    { model = 'sanctus',         name = 'Sanctus',                       brand = 'LCC'},
    { model = 'shotaro',         name = 'Shotaro',                       brand = 'Nagasaki'},
    { model = 'sovereign',       name = 'Sovereign',                     brand = 'WMC'},
    { model = 'stryder',         name = 'Stryder',                       brand = 'Nagasaki'},
    { model = 'thrust',          name = 'Thrust',                        brand = 'Dinka'},
    { model = 'vader',           name = 'Vader',                         brand = 'Shitzu'},
    { model = 'vindicator',      name = 'Vindicator',                    brand = 'Dinka'},
    { model = 'vortex',          name = 'Vortex',                        brand = 'Pegassi'},
    { model = 'wolfsbane',       name = 'Wolfsbane',                     brand = 'Western'},
    { model = 'zombiea',         name = 'Zombie Bobber',                 brand = 'Western'},
    { model = 'zombieb',         name = 'Zombie Chopper',                brand = 'Western'},
    { model = 'manchez2',        name = 'Manchez Scout',                 brand = 'Maibatsu'},
    { model = 'shinobi',         name = 'Shinobi',                       brand = 'Nagasaki'},
    { model = 'reever',          name = 'Reever',                        brand = 'Western'},
    { model = 'manchez3',        name = 'Manchez Scout Classic',         brand = 'Maibatsu'},
    { model = 'powersurge',      name = 'Powersurge',                    brand = 'Western'},
    { model = 'pizzaboy',        name = 'Pizza Boy',                     brand = 'Pegassi'},
    --- Off-Road (9)
    { model = 'bfinjection',     name = 'Bf Injection',                  brand = 'Annis'},
    { model = 'bifta',           name = 'Bifta',                         brand = 'Annis'},
    { model = 'blazer',          name = 'Blazer',                        brand = 'Annis'},
    { model = 'blazer2',         name = 'Blazer Lifeguard',              brand = 'Nagasaki'},
    { model = 'blazer3',         name = 'Blazer Hot Rod',                brand = 'Nagasaki'},
    { model = 'blazer4',         name = 'Blazer Sport',                  brand = 'Annis'},
    { model = 'blazer5',         name = 'Blazer Aqua',                   brand = 'Nagasaki'},
    { model = 'brawler',         name = 'Brawler',                       brand = 'Annis'},
    { model = 'caracara',        name = 'Caracara',                      brand = 'Vapid'},
    { model = 'caracara2',       name = 'Caracara 4x4',                  brand = 'Vapid'},
    { model = 'dubsta3',         name = 'Dubsta 6x6',                    brand = 'Annis'},
    { model = 'dune',            name = 'Dune Buggy',                    brand = 'Annis'},
    { model = 'everon',          name = 'Everon',                        brand = 'Karin'},
    { model = 'freecrawler',     name = 'Freecrawler',                   brand = 'Canis'},
    { model = 'hellion',         name = 'Hellion',                       brand = 'Annis'},
    { model = 'kalahari',        name = 'Kalahari',                      brand = 'Canis'},
    { model = 'kamacho',         name = 'Kamacho',                       brand = 'Canis'},
    { model = 'mesa3',           name = 'Mesa Merryweather',             brand = 'Canis'},
    { model = 'outlaw',          name = 'Outlaw',                        brand = 'Nagasaki'},
    { model = 'rancherxl',       name = 'Rancher XL',                    brand = 'Declasse'},
    { model = 'rebel2',          name = 'Rebel',                         brand = 'Vapid'},
    { model = 'riata',           name = 'Riata',                         brand = 'Vapid'},
    { model = 'sandking',        name = 'Sandking XL',                   brand = 'Vapid'},
    { model = 'sandking2',       name = 'Sandking SWB',                  brand = 'Vapid'},
    { model = 'trophytruck',     name = 'Trophy Truck',                  brand = 'Vapid'},
    { model = 'trophytruck2',    name = 'Desert Raid',                   brand = 'Vapid'},
    { model = 'vagrant',         name = 'Vagrant',                       brand = 'Maxwell'},
    { model = 'verus',           name = 'Verus',                         brand = 'Dinka'},
    { model = 'winky',           name = 'Winky',                         brand = 'Vapid'},
    { model = 'yosemite3',       name = 'Yosemite Rancher',              brand = 'Declasse'},
    { model = 'mesa',            name = 'Mesa',                          brand = 'Canis'},
    { model = 'ratel',           name = 'Ratel',                         brand = 'Vapid'},
    { model = 'l35',             name = 'Walton L35',                    brand = 'Declasse'},
    { model = 'monstrociti',     name = 'MonstroCiti',                   brand = 'Maibatsu'},
    { model = 'draugur',         name = 'Draugur',                       brand = 'Declasse'},
    { model = 'terminus',        name = 'Terminus',                      brand = 'Canis'},
    { model = 'yosemite4',       name = 'Yosemite 1500',                 brand = 'Declasse'},
    --- Industrial (10)
    { model = 'guardian',        name = 'Guardian',                      brand = 'Vapid'},
    { model = 'mixer2',          name = 'Mixer II',                      brand = 'HVY'},
    { model = 'tiptruck2',       name = 'Tipper II',                     brand = 'Brute'},
    { model = 'tiptruck',        name = 'Tipper',                        brand = 'Brute'},
    { model = 'rubble',          name = 'Rubble',                        brand = 'Jobuilt'},
    { model = 'mixer',           name = 'Mixer',                         brand = 'HVY'},
    { model = 'flatbed',         name = 'Flatbed Truck',                 brand = 'MTL'},
    { model = 'dump',            name = 'Dump Truck',                    brand = 'HVY'},
    { model = 'bulldozer',       name = 'Dozer',                         brand = 'HVY'},
    { model = 'handler',         name = 'Dock Handler',                  brand = 'HVY'},
    { model = 'cutter',          name = 'Cutter',                        brand = 'HVY'},
    --- Utility (11)
    { model = 'slamtruck',       name = 'Slam Truck',                    brand = 'Vapid'},
    { model = 'caddy3',          name = 'Caddy (Bunker)',                brand = 'Nagasaki'},
    { model = 'caddy2',          name = 'Caddy (Civilian)',              brand = 'Nagasaki'},
    { model = 'caddy3',          name = 'Caddy (Golf)',                  brand = 'Nagasaki'},
    { model = 'utillitruck',     name = 'Utility Truck (Cherry Picker)', brand = 'Brute'},
    { model = 'utillitruck2',    name = 'Utility Truck (Van)',           brand = 'Brute'},
    { model = 'utillitruck3',    name = 'Utility Truck (Contender)',     brand = 'Vapid'},
    { model = 'tractor',         name = 'Tractor',                       brand = 'Stanley'},
    { model = 'tractor2',        name = 'Fieldmaster',                   brand = 'Stanley'},
    { model = 'tractor3',        name = 'Fieldmaster',                   brand = 'Stanley'},
    { model = 'towtruck',        name = 'Tow Truck (Large)',             brand = 'Vapid'},
    { model = 'towtruck2',       name = 'Tow Truck (Small)',             brand = 'Vapid'},
    { model = 'scrap',           name = 'Scrap Truck',                   brand = 'Vapid'},
    { model = 'sadler',          name = 'Sadler',                        brand = 'Vapid'},
    { model = 'ripley',          name = 'Ripley',                        brand = 'HVY'},
    { model = 'mower',           name = 'Lawn Mower',                    brand = 'Jacksheepe'},
    { model = 'forklift',        name = 'Forklift',                      brand = 'HVY'},
    { model = 'docktug',         name = 'Docktug',                       brand = 'HVY'},
    { model = 'airtug',          name = 'Airtug',                        brand = 'HVY'},
    { model = 'trailers5',       name = 'Trailer (Christmas)',           brand = 'Unknown'},
    { model = 'tvtrailer2',      name = 'Trailer (TV)',                  brand = 'Unknown'},
    --- Vans (12)
    { model = 'bison',           name = 'Bison',                         brand = 'Bravado'},
    { model = 'bobcatxl',        name = 'Bobcat XL Open',                brand = 'Vapid'},
    { model = 'burrito3',        name = 'Burrito',                       brand = 'Declasse'},
    { model = 'gburrito2',       name = 'Burrito Custom',                brand = 'Declasse'},
    { model = 'rumpo',           name = 'Rumpo',                         brand = 'Bravado'},
    { model = 'journey',         name = 'Journey',                       brand = 'Zirconium'},
    { model = 'minivan',         name = 'Minivan',                       brand = 'Vapid'},
    { model = 'minivan2',        name = 'Minivan Custom',                brand = 'Vapid'},
    { model = 'paradise',        name = 'Paradise',                      brand = 'Bravado'},
    { model = 'rumpo3',          name = 'Rumpo Custom',                  brand = 'Bravado'},
    { model = 'speedo',          name = 'Speedo',                        brand = 'Vapid'},
    { model = 'speedo4',         name = 'Speedo Custom',                 brand = 'Vapid'},
    { model = 'surfer',          name = 'Surfer',                        brand = 'BF'},
    { model = 'youga3',          name = 'Youga Classic 4x4',             brand = 'Bravado'},
    { model = 'youga',           name = 'Youga',                         brand = 'Bravado'},
    { model = 'youga2',          name = 'Youga Classic',                 brand = 'Bravado'},
    { model = 'youga4',          name = 'Youga Custom',                  brand = 'Bravado'},
    { model = 'moonbeam',        name = 'Moonbeam',                      brand = 'Declasse'},
    { model = 'moonbeam2',       name = 'Moonbeam Custom',               brand = 'Declasse'},
    { model = 'boxville',        name = 'Boxville LSDWP',                brand = 'Brute'},
    { model = 'boxville2',       name = 'Boxville Go Postal',            brand = 'Brute'},
    { model = 'boxville3',       name = 'Boxville Humane Labs',          brand = 'Brute'},
    { model = 'boxville4',       name = 'Boxville Post OP',              brand = 'Brute'},
    { model = 'boxville5',       name = 'Armored Boxville',              brand = 'Brute',     },
    { model = 'pony',            name = 'Pony',                          brand = 'Brute'},
    { model = 'pony2',           name = 'Pony (Smoke on the water)',     brand = 'Brute'},
    { model = 'journey2',        name = 'Journey II',                    brand = 'Zirconium'},
    { model = 'surfer3',         name = 'Surfer Custom',                 brand = 'BF'},
    { model = 'speedo5',         name = 'Speedo Custom',                 brand = 'Vapid'},
    { model = 'mule2',           name = 'Mule',                          brand = 'Maibatsu'},
    { model = 'mule3',           name = 'Mule',                          brand = 'Maibatsu'},
    { model = 'taco',            name = 'Taco Truck',                    brand = 'Brute'},
    { model = 'boxville6',       name = 'Boxville (LSDS)',               brand = 'Brute'},
    --- Cycles (13)
    { model = 'bmx',             name = 'BMX',                           brand = 'Bike'},
    { model = 'cruiser',         name = 'Cruiser',                       brand = 'Bike'},
    { model = 'fixter',          name = 'Fixter',                        brand = 'Bike'},
    { model = 'scorcher',        name = 'Scorcher',                      brand = 'Bike'},
    { model = 'tribike',         name = 'Whippet Race Bike',             brand = 'Bike'},
    { model = 'tribike2',        name = 'Endurex Race Bike',             brand = 'Bike'},
    { model = 'tribike3',        name = 'Tri-Cycles Race Bike',          brand = 'Bike'},
    { model = 'inductor',        name = 'Inductor',                      brand = 'Coil'},
    { model = 'inductor2',       name = 'Junk Energy Inductor',          brand = 'Coil'},
    --- Boats (14)
    { model = 'avisa',           name = 'Avisa',                         brand = 'Kraken Subs'},
    { model = 'patrolboat',      name = 'Kurtz 31 Patrol Boat',          brand = 'Unknown'},
    { model = 'longfin',         name = 'Longfin',                       brand = 'Shitzu'},
    { model = 'tug',             name = 'Tug',                           brand = 'Buckingham'},
    { model = 'toro',            name = 'Toro',                          brand = 'Lampadati'},
    { model = 'toro2',           name = 'Toro Yacht',                    brand = 'Lampadati'},
    { model = 'submersible2',    name = 'Kraken',                        brand = 'Kraken Subs'},
    { model = 'speeder',         name = 'Speeder',                       brand = 'Pegassi'},
    { model = 'speeder2',        name = 'Speeder Yacht',                 brand = 'Pegassi'},
    { model = 'tropic',          name = 'Tropic',                        brand = 'Shitzu'},
    { model = 'tropic2',         name = 'Tropic Yacht',                  brand = 'Shitzu'},
    { model = 'suntrap',         name = 'Suntrap',                       brand = 'Shitzu'},
    { model = 'submersible',     name = 'Submersible',                   brand = 'Kraken Subs'},
    { model = 'squalo',          name = 'Squalo',                        brand = 'Shitzu'},
    { model = 'seashark',        name = 'Seashark',                      brand = 'Speedophile'},
    { model = 'seashark3',       name = 'Seashark Yacht',                brand = 'Speedophile'},
    { model = 'marquis',         name = 'Marquis',                       brand = 'Dinka'},
    { model = 'jetmax',          name = 'Jetmax',                        brand = 'Shitzu'},
    { model = 'dinghy',          name = 'Dinghy 2-Seater',               brand = 'Nagasaki'},
    { model = 'dinghy2',         name = 'Dinghy 4-Seater',               brand = 'Nagasaki'},
    { model = 'dinghy3',         name = 'Dinghy (Heist)',                brand = 'Nagasaki'},
    { model = 'dinghy4',         name = 'Dinghy Yacht',                  brand = 'Nagasaki'},
    --- Helicopters (15)
    { model = 'conada2',         name = 'Weaponized Conada',             brand = 'Buckingham'},
    { model = 'conada',          name = 'Conada',                        brand = 'Buckingham'},
    { model = 'seasparrow2',     name = 'Sparrow',                       brand = 'Unknown'},
    { model = 'annihilator2',    name = 'Annihilator Stealth',           brand = 'Western Company'},
    { model = 'seasparrow',      name = 'Sea Sparrow',                   brand = 'Unknown'},
    { model = 'akula',           name = 'Akula',                         brand = 'Unknown'},
    { model = 'hunter',          name = 'FH-1 Hunter',                   brand = 'Unknown'},
    { model = 'havok',           name = 'Havok',                         brand = 'Nagasaki'},
    { model = 'volatus',         name = 'Volatus',                       brand = 'Buckingham'},
    { model = 'supervolito2',    name = 'SuperVolito Carbon',            brand = 'Buckingham'},
    { model = 'supervolito',     name = 'SuperVolito',                   brand = 'Buckingham'},
    { model = 'swift2',          name = 'Swift Deluxe',                  brand = 'Buckingham'},
    { model = 'valkyrie',        name = 'Valkyrie',                      brand = 'Buckingham'},
    { model = 'savage',          name = 'Savage',                        brand = 'Unknown'},
    { model = 'swift',           name = 'Swift',                         brand = 'Buckingham'},
    { model = 'annihilator',     name = 'Annihilator',                   brand = 'Western Company'},
    { model = 'cargobob2',       name = 'Cargobob Jetsam',               brand = 'Western Company'},
    { model = 'skylift',         name = 'Skylift',                       brand = 'HVY'},
    { model = 'maverick',        name = 'Maverick',                      brand = 'Buckingham'},
    { model = 'frogger',         name = 'Frogger',                       brand = 'Maibatsu'},
    { model = 'frogger2',        name = 'Frogger',                       brand = 'Maibatsu'},
    { model = 'cargobob',        name = 'Cargobob',                      brand = 'Western Company'},
    { model = 'cargobob3',       name = 'Cargobob',                      brand = 'Western Company'},
    { model = 'seasparrow3',     name = 'Sparrow (Prop)',                brand = 'Unknown'},
    { model = 'buzzard',         name = 'Buzzard Attack Chopper',        brand = 'Nagasaki'},
    { model = 'buzzard2',        name = 'Buzzard',                       brand = 'Nagasaki'},
    --- Planes (16)
    { model = 'streamer216',     name = 'Streamer216',                   brand = 'Mammoth'},
    { model = 'raiju',           name = 'F-160 Raiju',                   brand = 'Mammoth'},
    { model = 'alkonost',        name = 'RO-86 Alkonost',                brand = 'Unknown'},
    { model = 'strikeforce',     name = 'B-11 Strikeforce',              brand = 'Unknown'},
    { model = 'blimp3',          name = 'Blimp',                         brand = 'Unknown'},
    { model = 'avenger',         name = 'Avenger',                       brand = 'Mammoth'},
    { model = 'avenger2',        name = 'Avenger',                       brand = 'Mammoth'},
    { model = 'volatol',         name = 'Volatol',                       brand = 'Unknown'},
    { model = 'nokota',          name = 'P-45 Nokota',                   brand = 'Unknown'},
    { model = 'seabreeze',       name = 'Seabreeze',                     brand = 'Western Company'},
    { model = 'pyro',            name = 'Pyro',                          brand = 'Buckingham'},
    { model = 'mogul',           name = 'Mogul',                         brand = 'Mammoth'},
    { model = 'howard',          name = 'Howard NX-25',                  brand = 'Unknown'},
    { model = 'bombushka',       name = 'RM-10 Bombushka',               brand = 'Unknown'},
    { model = 'molotok',         name = 'V-65 Molotok',                  brand = 'Unknown'},
    { model = 'microlight',      name = 'Ultralight',                    brand = 'Unknown'},
    { model = 'tula',            name = 'Tula',                          brand = 'Mammoth'},
    { model = 'rogue',           name = 'Rogue',                         brand = 'Western Company'},
    { model = 'starling',        name = 'LF-22 Starling',                brand = 'Unknown'},
    { model = 'alphaz1',         name = 'Alpha-Z1',                      brand = 'Buckingham'},
    { model = 'nimbus',          name = 'Nimbus',                        brand = 'Buckingham'},
    { model = 'luxor2',          name = 'Luxor Deluxe',                  brand = 'Buckingham'},
    { model = 'velum2',          name = 'Velum 5-seater',                brand = 'JoBuilt'},
    { model = 'hydra',           name = 'Hydra',                         brand = 'Mammoth'},
    { model = 'blimp2',          name = 'Xero Blimp',                    brand = 'Unknown'},
    { model = 'dodo',            name = 'Dodo',                          brand = 'Mammoth'},
    { model = 'miljet',          name = 'Miljet',                        brand = 'Buckingham'},
    { model = 'besra',           name = 'Besra',                         brand = 'Western Company'},
    { model = 'vestra',          name = 'Vestra',                        brand = 'Buckingham'},
    { model = 'cargoplane',      name = 'Cargo Plane',                   brand = 'JoBuilt'},
    { model = 'velum',           name = 'Velum',                         brand = 'JoBuilt'},
    { model = 'titan',           name = 'Titan',                         brand = 'Unknown'},
    { model = 'shamal',          name = 'Shamal',                        brand = 'Buckingham'},
    { model = 'lazer',           name = 'P-996 Lazer',                   brand = 'JoBuilt'},
    { model = 'mammatus',        name = 'Mammatus',                      brand = 'JoBuilt'},
    { model = 'stunt',           name = 'Mallard',                       brand = 'Western Company'},
    { model = 'luxor',           name = 'Luxor',                         brand = 'Buckingham'},
    { model = 'jet',             name = 'Jet',                           brand = 'Unknown'},
    { model = 'duster',          name = 'Duster',                        brand = 'Western Company'},
    { model = 'cuban800',        name = 'Cuban 800',                     brand = 'Western Company'},
    { model = 'blimp',           name = 'Atomic Blimp',                  brand = 'Unknown'},
    --- Service (17)
    { model = 'brickade',        name = 'Brickade',                      brand = 'MTL'},
    { model = 'brickade2',       name = 'Brickade 6x6',                  brand = 'MTL'},
    { model = 'pbus2',           name = 'Festival Bus',                  brand = 'Unknown'},
    { model = 'wastelander',     name = 'Wastelander',                   brand = 'MTL'},
    { model = 'rallytruck',      name = 'Dune',                          brand = 'MTL'},
    { model = 'metrotrain',      name = 'Metro Train',                   brand = 'Unknown'},
    { model = 'freight',         name = 'Freight Train',                 brand = 'Unknown'},
    { model = 'cablecar',        name = 'Cable Car',                     brand = 'Unknown'},
    { model = 'trash',           name = 'Trashmaster',                   brand = 'JoBuilt'},
    { model = 'trash2',          name = 'Trashmaster',                   brand = 'JoBuilt'},
    { model = 'tourbus',         name = 'Tour Bus',                      brand = 'Brute'},
    { model = 'taxi',            name = 'Taxi',                          brand = 'Vapid'},
    { model = 'rentalbus',       name = 'Rental Shuttle Bus',            brand = 'Brute'},
    { model = 'coach',           name = 'Dashound',                      brand = 'Brute'},
    { model = 'bus',             name = 'Bus',                           brand = 'Brute'},
    { model = 'airbus',          name = 'Airport Bus',                   brand = 'Brute'},
    --- Emergency (18)
    { model = 'riot',            name = 'Police Riot',                   brand = 'Brute'},
    { model = 'riot2',           name = 'RCV',                           brand = 'Unknown'},
    { model = 'pbus',            name = 'Police Prison Bus',             brand = 'Vapid'},
    { model = 'police',          name = 'Police Cruiser',                brand = 'Vapid'},
    { model = 'police2',         name = 'Police Buffalo',                brand = 'Vapid'},
    { model = 'police3',         name = 'Police Interceptor',            brand = 'Vapid'},
    { model = 'police4',         name = 'Unmarked Cruiser',              brand = 'Vapid'},
    { model = 'sheriff',         name = 'Sheriff SUV',                   brand = 'Declasse'},
    { model = 'sheriff2',        name = 'Sheriff Cruiser',               brand = 'Vapid'},
    { model = 'policeold1',      name = 'Police Rancher',                brand = 'Declasse'},
    { model = 'policeold2',      name = 'Police Roadcruiser',            brand = 'Albany'},
    { model = 'policet',         name = 'Police Transporter',            brand = 'Vapid'},
    { model = 'policeb',         name = 'Police Bike',                   brand = 'Vapid'},
    { model = 'polmav',          name = 'Police Maverick',               brand = 'Buckingham'},
    { model = 'ambulance',       name = 'Ambulance',                     brand = 'Brute'},
    { model = 'firetruk',        name = 'Fire Truck',                    brand = 'MTL'},
    { model = 'lguard',          name = 'Lifeguard',                     brand = 'Declasse'},
    { model = 'seashark2',       name = 'Seashark Lifeguard',            brand = 'Speedophile'},
    { model = 'pranger',         name = 'Park Ranger',                   brand = 'Declasse'},
    { model = 'fbi',             name = 'FIB Buffalo',                   brand = 'Bravado'},
    { model = 'fbi2',            name = 'FIB Granger',                   brand = 'Declasse'},
    { model = 'predator',        name = 'Police Predator',               brand = 'Unknown'},
    { model = 'polgauntlet',     name = 'Gauntlet Interceptor',          brand = 'Bravado'},
    { model = 'police5',         name = 'Stanier LE Cruiser',            brand = 'Vapid'},
    { model = 'polimpaler5',     name = 'Impaler SZ Cruiser',            brand = 'Declasse'},
    { model = 'polimpaler6',     name = 'Impaler LX Cruiser',            brand = 'Declasse'},
    { model = 'poldominator10',  name = 'Dominator FX Interceptor',      brand = 'Vapid'},
    { model = 'policet3',        name = 'Burrito (Bail Enforcement)',    brand = 'Declasse'},
    { model = 'polgreenwood',    name = 'Greenwood Cruiser',             brand = 'Bravado'},
    { model = 'poldorado',       name = 'Dorado Cruiser',                brand = 'Vapid'},
    --- Military (19)
    { model = 'vetir',           name = 'Vetir',                         brand = 'Unknown'},
    { model = 'kosatka',         name = 'Kosatka',                       brand = 'Rune'},
    { model = 'minitank',        name = 'RC Tank',                       brand = 'Unknown'},
    { model = 'scarab',          name = 'Scarab',                        brand = 'HVY'},
    { model = 'terbyte',         name = 'Terrorbyte',                    brand = 'Benefactor'},
    { model = 'thruster',        name = 'Thruster',                      brand = 'Mammoth'},
    { model = 'khanjali',        name = 'TM-02 Khanjali Tank',           brand = 'Unknown'},
    { model = 'chernobog',       name = 'Chernobog',                     brand = 'HVY'},
    { model = 'barrage',         name = 'Barrage',                       brand = 'HVY'},
    { model = 'trailerlarge',    name = 'Mobile Operations Center',      brand = 'Unknown'},
    { model = 'halftrack',       name = 'Half-track',                    brand = 'Bravado'},
    { model = 'apc',             name = 'APC Tank',                      brand = 'HVY'},
    { model = 'trailersmall2',   name = 'Anti-Aircraft Trailer',         brand = 'Vom Feuer'},
    { model = 'rhino',           name = 'Rhino Tank',                    brand = 'Unknown'},
    { model = 'crusader',        name = 'Crusader',                      brand = 'Canis'},
    { model = 'barracks',        name = 'Barracks',                      brand = 'HVY'},
    { model = 'barracks2',       name = 'Barracks Semi',                 brand = 'HVY'},
    { model = 'barracks3',       name = 'Barracks',                      brand = 'HVY'},
    --- Commercial (20)
    { model = 'cerberus',        name = 'Apocalypse Cerberus',           brand = 'MTL'},
    { model = 'pounder2',        name = 'Pounder Custom',                brand = 'MTL'},
    { model = 'mule4',           name = 'Mule Custom',                   brand = 'Maibatsu'},
    { model = 'phantom3',        name = 'Phantom Custom',                brand = 'Jobuilt'},
    { model = 'hauler2',         name = 'Hauler Custom',                 brand = 'Jobuilt'},
    { model = 'phantom2',        name = 'Phantom Wedge',                 brand = 'Jobuilt'},
    { model = 'mule5',           name = 'Mule (Heist)',                  brand = 'Maibatsu'},
    { model = 'stockade',        name = 'Stockade',                      brand = 'Brute'},
    { model = 'pounder',         name = 'Pounder',                       brand = 'MTL'},
    { model = 'phantom',         name = 'Phantom',                       brand = 'Jobuilt'},
    { model = 'packer',          name = 'Packer',                        brand = 'MTL'},
    { model = 'mule',            name = 'Mule',                          brand = 'Maibatsu'},
    { model = 'hauler',          name = 'Hauler',                        brand = 'Jobuilt'},
    { model = 'biff',            name = 'Biff',                          brand = 'Brute'},
    { model = 'benson',          name = 'Benson',                        brand = 'Vapid'},
    { model = 'benson2',         name = 'Benson (Cluckin Bell)',         brand = 'Vapid'},
    { model = 'phantom4',        name = 'Phantom (Christmas)',           brand = 'Vapid'},
    --- Trains (21)
    --- Open Wheel (22)
    { model = 'openwheel2',      name = 'DR1',                           brand = 'Declasse'},
    { model = 'openwheel1',      name = 'BR8',                           brand = 'Benefactor'},
    { model = 'formula2',        name = 'R88',                           brand = 'Ocelot'},
    { model = 'formula',         name = 'PR4',                           brand = 'Progen'},
}
